ansible_become: true
ansible_user: ubuntu
ansible_ssh_common_args: "-o HostKeyAlias={{ fqdn }}"

fqdn: oci.justanother.engineer
letsencrypt_email: "luiz@justanother.engineer"

oci_iptables_ssh_ingress_cidr: "{{ lookup('env', 'TF_VAR_ssh_ingress_cidr') | default('0.0.0.0/0', true) }}"
oci_iptables_rules_path: /etc/iptables/rules.v4
oci_iptables_packages:
  - iptables
  - iptables-persistent
oci_iptables_allowed_tcp_ports:
  - 80
  - 443
